# Generated by Django 5.0.7 on 2024-07-22 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipecomponents',
            name='ingredients_list',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user_ingredients_list',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user_recipe_list',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='culinarian',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='recipe_components_list',
        ),
        migrations.DeleteModel(
            name='IngredientUnit',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='Recipe',
        ),
        migrations.DeleteModel(
            name='RecipeComponents',
        ),
    ]
