# Generated by Django 5.0.7 on 2024-07-29 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='ingredients_list',
            new_name='ingredientsList',
        ),
    ]
