# Generated by Django 5.0.7 on 2024-07-29 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_ingredients_list_profile_ingredientslist'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='shoppingList',
            field=models.ManyToManyField(blank=True, related_name='shoppingList', to='api.ingredient'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='ingredientsList',
            field=models.ManyToManyField(blank=True, related_name='ingredientsList', to='api.ingredient'),
        ),
    ]
