# Generated by Django 5.0.7 on 2024-07-30 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_recipe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='status',
            new_name='privacy',
        ),
    ]
