# Generated by Django 5.0.7 on 2024-08-06 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='ingredients_list',
            new_name='ingredientsList',
        ),
        migrations.RenameField(
            model_name='recipecomponents',
            old_name='ingredients_list',
            new_name='ingredientsList',
        ),
    ]
