# Generated by Django 5.0.7 on 2024-08-11 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_rename_ingredients_list_recipe_ingredientslist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='steps',
            name='title',
            field=models.CharField(default='', max_length=50),
        ),
    ]
