# Generated by Django 5.0.7 on 2024-08-12 22:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_review'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='reviews', to=settings.AUTH_USER_MODEL),
        ),
    ]
