# Generated by Django 5.0.7 on 2024-08-12 22:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_review_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='review', to=settings.AUTH_USER_MODEL),
        ),
    ]
