# Generated by Django 5.0.7 on 2024-08-18 16:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_recipe_rating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='reviewers',
            field=models.ManyToManyField(blank=True, related_name='reviewed_recipes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredientsList',
            field=models.ManyToManyField(blank=True, to='api.ingredient'),
        ),
        migrations.AlterField(
            model_name='recipecomponents',
            name='ingredientsList',
            field=models.ManyToManyField(blank=True, to='api.ingredientunit'),
        ),
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
