# Generated by Django 5.0.7 on 2024-08-18 20:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_recipe_reviewers_alter_recipe_ingredientslist_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='unique_review_per_user_per_recipe'),
        ),
    ]
